// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: movies.sql

package db

import (
	"context"
)

const getMovieByID = `-- name: GetMovieByID :one
SELECT
    id,
    title,
    year,
    director
FROM movies
WHERE id = $1
`

func (q *Queries) GetMovieByID(ctx context.Context, id int32) (Movie, error) {
	row := q.db.QueryRow(ctx, getMovieByID, id)
	var i Movie
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Year,
		&i.Director,
	)
	return i, err
}
